// mod delete;
mod get;
// mod post;
// pub use delete::delete_team;
pub use get::get_teams;
// mod put;
// pub use post::post_team;
// mod payload;
// pub use payload::TeamInputPayload;
// pub use put::put_team;
