app_settings:
  host: 127.0.0.1
  port: 8000

qgis_server:
  figure_config:
    logo_filename: "logo_edf_power_solutions_RGB.svg"
    logo_height_pixels: 296
    logo_width_pixels: 678
    north_arrow_filename: "NorthArrow_11.svg"
    north_arrow_height_pixels: 77
    north_arrow_width_pixels: 61
