import type ProjectInputDTO from "@/domain/project/inputDTO";
import { TextInput } from "../../../../components/forms/components/TextInput";
import { ModalForm } from "../../../../components/forms/ModalForm";
import { usePostProject } from "../../../../hooks/api/usePostProject";
import { slugify } from "@/lib/slugify";
import { CountrySelect } from "@/components/forms/components/CountrySelector";
import { FaCircleInfo } from "react-icons/fa6";
import { Select } from "@/components/forms/components/Select";
import { Visibility } from "@/domain/types";
import { useForm } from "react-hook-form";
import type User from "@/domain/user/entity";
import type { TechnologyOutputDto } from "@/domain/technology/outputDto";

interface CreateProjectFormData {
  projectName: string;
  country: string;
  srid: number | "";
  visibility: Visibility;
  technologies: TechnologyOutputDto[];
}

interface Props {
  currentUser: User;
  technologies: TechnologyOutputDto[];
}

export const CreateProjectForm = ({ currentUser, technologies }: Props) => {
  const postProject = usePostProject();
  const defautlSrid = currentUser.operatingCountryId === "GB" ? 27700 : "";

  const { handleSubmit, watch, reset, setValue } =
    useForm<CreateProjectFormData>({
      defaultValues: {
        projectName: "",
        country: currentUser.operatingCountryId,
        srid: defautlSrid,
        visibility: Visibility.Private,
      },
    });

  const projectName = watch("projectName");
  const country = watch("country");
  const srid = watch("srid");
  const slug = slugify(projectName);

  const handleCountryChange = (val: string) => {
    setValue("country", val);
    if (val === "GB") {
      setValue("srid", 27700);
    } else {
      setValue("srid", "");
    }
  };

  const onSubmit = async (data: CreateProjectFormData) => {
    const dto: ProjectInputDTO = {
      name: data.projectName,
      slug: slug,
      country_code: data.country,
    };

    await postProject.mutateAsync(dto);
  };

  const onReset = () => {
    reset();
  };

  return (
    <ModalForm
      id="create_project"
      title="Create project"
      onSubmit={handleSubmit(onSubmit)}
      onReset={onReset}
    >
      <div className="flex flex-col gap-2">
        <TextInput
          name="projectName"
          label="Project name"
          required
          value={projectName}
          onChange={(val) => setValue("projectName", val)}
        />

        <TextInput
          name="slug"
          label="URL"
          bottomLabel="Autogenerated from project name"
          required
          placeholder="URL"
          disabled
          value={slug}
        />
        <CountrySelect value={country} onChange={handleCountryChange} />

        <TextInput
          name="srid"
          label="Coordinate Reference System ID"
          placeholder="CRS ID"
          type="number"
          bottomLabel="Optional (recommended)"
          step={1}
          value={srid}
          onChange={(val) => setValue("srid", val === "" ? "" : Number(val))}
        >
          <div className="dropdown dropdown-end">
            <div
              tabIndex={0}
              role="button"
              className="btn btn-circle btn-ghost btn-xs text-info"
            >
              <FaCircleInfo size={18} />
            </div>
            <div
              tabIndex={0}
              className="card card-sm dropdown-content bg-base-100 rounded-box z-1 w-64 shadow-sm"
            >
              <div tabIndex={0} className="card-body">
                <h2 className="card-title"></h2>
                <p>TLDR: Set as 27700 for UK projects</p>
              </div>
            </div>
          </div>
        </TextInput>
        <Select
          name="visibility"
          label="Visibility"
          defaultValue={Visibility.Private}
        >
          <option key={Visibility.Team} value={Visibility.Team}>
            Team (visible to you and your team)
          </option>
          <option key={Visibility.Public} value={Visibility.Public}>
            Public (visible to whole organisation)
          </option>
          <option key={Visibility.Private} value={Visibility.Private}>
            Private (only visible to you)
          </option>
        </Select>
        <fieldset className="fieldset bg-base-100 border-base-300 rounded-box border p-4">
          <legend className="fieldset-legend">Technologies</legend>
          {technologies.map((t) => (
            <label key={t.id} className="label">
              <input type="checkbox" className="checkbox checkbox-sm" />
              <span className="label-text">{t.name}</span>
            </label>
          ))}
          select all that apply
        </fieldset>
      </div>
    </ModalForm>
  );
};
