import type { Control, UseFormSetValue, UseFormWatch } from "react-hook-form";
import { Controller } from "react-hook-form";
import { TextInput } from "@/components/forms/components/TextInput";
import { CountrySelect } from "@/components/forms/components/CountrySelector";
import { Select } from "@/components/forms/components/Select";
import { FaCircleInfo } from "react-icons/fa6";
import { Visibility, VisibilityConfig } from "@/domain/types";
import type { TechnologyOutputDto } from "@/domain/technology/outputDto";
import { slugify } from "@/lib/slugify";

export interface ProjectFormData {
  projectName: string;
  country: string;
  srid: number | "";
  visibility: Visibility;
  technologies: number[];
}

interface ProjectFormProps {
  control: Control<ProjectFormData>;
  watch: UseFormWatch<ProjectFormData>;
  setValue: UseFormSetValue<ProjectFormData>;
  technologies: TechnologyOutputDto[];
}

export const ProjectForm = ({
  control,
  watch,
  setValue,
  technologies,
}: ProjectFormProps) => {
  const projectName = watch("projectName");
  const slug = slugify(projectName);

  const priv = VisibilityConfig[Visibility.Private];
  const team = VisibilityConfig[Visibility.Team];
  const pub = VisibilityConfig[Visibility.Public];

  return (
    <div className="flex flex-col gap-2">
      <Controller
        name="projectName"
        control={control}
        rules={{ required: true }}
        render={({ field }) => (
          <TextInput
            name="projectName"
            label="Project name"
            required
            value={field.value}
            onChange={field.onChange}
          />
        )}
      />

      <TextInput
        name="slug"
        label="URL"
        bottomLabel="Autogenerated from project name"
        required
        placeholder="URL"
        disabled
        value={slug}
      />

      <Controller
        name="country"
        control={control}
        render={({ field }) => (
          <CountrySelect
            name="country"
            value={field.value}
            onChange={(val) => {
              field.onChange(val);
              if (val === "GB") {
                setValue("srid", 27700);
              } else {
                setValue("srid", "");
              }
            }}
          />
        )}
      />

      <Controller
        name="srid"
        control={control}
        render={({ field }) => (
          <TextInput
            name="srid"
            label="Coordinate Reference System ID"
            placeholder="Optional (recommended)"
            type="number"
            step={1}
            value={field.value}
            onChange={(val) => field.onChange(val === "" ? "" : Number(val))}
            max={900913}
            min={2000}
          >
            <div className="dropdown dropdown-end">
              <div
                tabIndex={0}
                role="button"
                className="btn btn-circle btn-ghost btn-xs text-info"
              >
                <FaCircleInfo size={18} />
              </div>
              <div
                tabIndex={0}
                className="card card-sm dropdown-content bg-base-100 rounded-box z-1 w-64 shadow-sm"
              >
                <div tabIndex={0} className="card-body">
                  <h2 className="card-title"></h2>
                  <p>TLDR: Set as 27700 for UK projects</p>
                </div>
              </div>
            </div>
          </TextInput>
        )}
      />

      <Controller
        name="visibility"
        control={control}
        render={({ field }) => (
          <Select
            name="visibility"
            label="Visibility"
            value={field.value}
            onChange={field.onChange}
          >
            <option value={Visibility.Team}>
              {`${team.label} (${team.description})`}
            </option>
            <option value={Visibility.Public}>
              {`${pub.label} (${pub.description})`}
            </option>
            <option value={Visibility.Private}>
              {`${priv.label} (${priv.description})`}
            </option>
          </Select>
        )}
      />

      <Controller
        name="technologies"
        control={control}
        render={({ field }) => (
          <fieldset className="fieldset bg-base-100 border-base-300 rounded-box border p-4">
            <legend className="fieldset-legend">Technologies</legend>
            {technologies.map((t) => (
              <label
                key={t.id}
                className="label cursor-pointer justify-start gap-2"
              >
                <input
                  type="checkbox"
                  className="checkbox checkbox-sm"
                  checked={field.value.includes(t.id)}
                  onChange={(e) => {
                    const updatedValue = e.target.checked
                      ? [...field.value, t.id]
                      : field.value.filter((id) => id !== t.id);
                    field.onChange(updatedValue);
                  }}
                />
                <span className="label-text">{t.name}</span>
              </label>
            ))}
            <p className="text-sm text-base-content/70 mt-2">
              Select all that apply
            </p>
          </fieldset>
        )}
      />
    </div>
  );
};
